### ISSUE TITLE
Fatal error Drupal 8.5+

### ISSUE THREAD

**Issue by zweishar** [droath/pattern_library#6]
Module works great in Drupal 8.4, but is broken after upgrade to 8.5.

Issue occurs in `layout_discovery.module` line 44 in `template_preprocess_layout` where `$variables['content']` is not set.

I have tested the default display suite layouts and they do not experience this problem, which leads me to believe the issue is in `pattern_library`.

The change that broke this module does not appear to be in the `layout_discovery.module` itself as I installed the version in 8.4 on an 8.5 site and still hit the issue (also there isn't much change in the module between 8.4 and 8.5).

In 8.4, `template_preprocess_layout()` is never called during a page render involving `pattern_library`. This leads me to believe that https://www.drupal.org/node/2861840 might be involved.

**Comment by droath** [comment]
@zweishar 

Thanks for reporting the issue! With your discovery work I was able to narrow down the problem a lot faster. You were right, it was a problem with the `base hook` preprocess never getting called in prior Drupal versions. 

**Bug Explanation:** 

Due to us not needing to conform our pattern layout structure to be based on the Drupal specification, there is no need for the `layout` `base hook` preprocess to be invoked. The `base hook ` is defined for all templates that are registered via the layout definition. Which we can easily define our own theme template ourself in the `theme_hook`, which we already do.  So after making some minor changes everything is now working as it should.
